package capstone.allbom.job.domain;

public enum Province {
    SEOUL, BUSAN, DAEGU, INCHEON, GWANGJU, DAEJEON, ULSAN, SEJONG, GYEONGGI, CHUNGBUK, CHUNGNAM, JEONNAM, GYEONGBUK, GYEONGNAM, JEJU, GANGWON, JEONBUK
}
