name: be-docker-buildx-ci

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'backend/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: eunsun2080/allbom:latest
          platforms: linux/amd64
          build-args: |
            "ENCRYPT_KEY=${{ secrets.ENCRYPT_KEY }}"
